---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: resource-scaler
  namespace: default
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments/scale", "replicasets/scale", "statefulsets/scale"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-application-controller-resource-scaler
  namespace: default
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: default
roleRef:
  kind: Role
  name: resource-scaler
  apiGroup: rbac.authorization.k8s.io