apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: one-resources
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |-
        resources:
          requests:
            cpu: '10000m'
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps/
    targetRevision: HEAD
