apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: four-parent-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: example-yaml/argoapp/
    repoURL: https://github.com/todaywasawesome/troubleshooting-argocd/
    targetRevision: demo
